"""phase_3_instruments

Revision ID: 02e368dbf7e0
Revises: 490f97c8e4f3
Create Date: 2026-08-18 04:34:05.152873

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "02e368dbf7e0"
down_revision: Union[str, None] = "490f97c8e4f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instruments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("exchange", sa.String(length=20), nullable=False),
        sa.Column("underlying", sa.String(length=50), nullable=False),
        sa.Column("trading_symbol", sa.String(length=50), nullable=False),
        sa.Column(
            "instrument_type",
            sa.Enum("FUTURE", "OPTION", name="instrumenttype"),
            nullable=False,
        ),
        sa.Column("option_type", sa.Enum("CE", "PE", name="optiontype"), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("strike_price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("lot_size", sa.Integer(), nullable=False),
        sa.Column("tick_size", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("broker_instrument_token", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_instruments_broker_instrument_token"),
        "instruments",
        ["broker_instrument_token"],
        unique=False,
    )
    op.create_index(
        op.f("ix_instruments_exchange"), "instruments", ["exchange"], unique=False
    )
    op.create_index(
        op.f("ix_instruments_expiry_date"), "instruments", ["expiry_date"], unique=False
    )
    op.create_index(
        op.f("ix_instruments_instrument_type"),
        "instruments",
        ["instrument_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_instruments_option_type"), "instruments", ["option_type"], unique=False
    )
    op.create_index(
        op.f("ix_instruments_strike_price"),
        "instruments",
        ["strike_price"],
        unique=False,
    )
    op.create_index(
        op.f("ix_instruments_trading_symbol"),
        "instruments",
        ["trading_symbol"],
        unique=True,
    )
    op.create_index(
        op.f("ix_instruments_underlying"), "instruments", ["underlying"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_instruments_underlying"), table_name="instruments")
    op.drop_index(op.f("ix_instruments_trading_symbol"), table_name="instruments")
    op.drop_index(op.f("ix_instruments_strike_price"), table_name="instruments")
    op.drop_index(op.f("ix_instruments_option_type"), table_name="instruments")
    op.drop_index(op.f("ix_instruments_instrument_type"), table_name="instruments")
    op.drop_index(op.f("ix_instruments_expiry_date"), table_name="instruments")
    op.drop_index(op.f("ix_instruments_exchange"), table_name="instruments")
    op.drop_index(
        op.f("ix_instruments_broker_instrument_token"), table_name="instruments"
    )
    op.drop_table("instruments")
    # ### end Alembic commands ###
