"""phase_2_domain_models

Revision ID: 490f97c8e4f3
Revises:
Create Date: 2026-08-18 04:31:26.062846

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "490f97c8e4f3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "challenges",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "starting_capital", sa.Numeric(precision=14, scale=2), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("TRADER", "SUPPORT", "COMPLIANCE", "ADMIN", name="role"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "rule_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("challenge_id", sa.Uuid(), nullable=False),
        sa.Column(
            "account_type_scope",
            sa.Enum("EVALUATION", "FUNDED", name="accounttype"),
            nullable=False,
        ),
        sa.Column(
            "profit_target_percent", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column(
            "max_daily_loss_percent", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column(
            "max_drawdown_percent", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column("min_trading_days", sa.Integer(), nullable=False),
        sa.Column(
            "funded_capital_amount", sa.Numeric(precision=14, scale=2), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["challenge_id"],
            ["challenges.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "accounts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("challenge_id", sa.Uuid(), nullable=False),
        sa.Column("rule_version_id", sa.Uuid(), nullable=False),
        sa.Column("source_evaluation_account_id", sa.Uuid(), nullable=True),
        sa.Column(
            "account_type",
            sa.Enum("EVALUATION", "FUNDED", name="accounttype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING_ACTIVATION",
                "ACTIVE",
                "FAILED",
                "PASSED",
                "SUSPENDED",
                "CLOSED",
                name="accountstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "starting_balance", sa.Numeric(precision=14, scale=2), nullable=False
        ),
        sa.Column("current_balance", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("equity", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("floating_pnl", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("daily_pnl", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("high_water_mark", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("drawdown_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("drawdown_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("trading_days_count", sa.Integer(), nullable=False),
        sa.Column("execution_provider_key", sa.String(length=50), nullable=True),
        sa.Column("broker_account_ref", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["challenge_id"],
            ["challenges.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rule_version_id"],
            ["rule_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_evaluation_account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("accounts")
    op.drop_table("rule_versions")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("challenges")
    # ### end Alembic commands ###
