import logging
import uuid
from decimal import Decimal
from typing import Optional

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.constants import InstrumentType, OrderSide, OrderStatus
from app.execution.provider_factory import ExecutionProviderFactory
from app.market_data.redis_cache import MarketDataCache
from app.models.account import Account
from app.models.instrument import Instrument
from app.models.ledger import LedgerEntry
from app.models.order import Order
from app.models.position import Position
from app.models.trade import Trade
from app.risk.engine import risk_engine
from app.schemas.order import OrderCreate
from app.services.broadcast_service import broadcast_service
from app.services.pnl_service import PnLEngine

logger = logging.getLogger(__name__)


class OrderService:
    @staticmethod
    async def place_order(
        db: AsyncSession, account_id: uuid.UUID, order_in: OrderCreate
    ) -> Order:
        # Validate instrument
        """Place a new order request and route it through the execution flow."""
        instrument = await db.get(Instrument, order_in.instrument_id)
        if not instrument:
            raise ValueError("Instrument not found")
        if instrument.instrument_type != InstrumentType.OPTION:
            raise ValueError("Only option-chain instruments can be traded")

        # Validate account
        account = await db.get(Account, account_id)
        if not account:
            raise ValueError("Account not found")

        # Create order record
        order = Order(
            account_id=account_id,
            instrument_id=instrument.id,
            side=order_in.side,
            order_type=order_in.order_type,
            quantity=order_in.quantity,
            price=order_in.price,
            trigger_price=order_in.trigger_price,
            status=OrderStatus.OPEN,
        )

        # Attach symbol for matching engine
        setattr(order, "_instrument_symbol", instrument.trading_symbol)

        # Pre-trade risk check
        quote = await MarketDataCache.get_quote(instrument.trading_symbol)
        allowed, reason = await risk_engine.check_pre_trade(
            db, account, order, instrument, quote.ltp if quote else None
        )
        if not allowed:
            order.status = OrderStatus.REJECTED
            order.rejection_reason = reason
            db.add(order)
            await db.commit()
            raise ValueError(reason)

        db.add(order)
        # Flush to get ID
        await db.flush()

        # Send to execution provider based on Account Type
        provider = ExecutionProviderFactory.get_provider(account.account_type)
        success, message = await provider.submit_order(order)

        if success and order.status in [
            OrderStatus.FILLED,
            OrderStatus.PARTIALLY_FILLED,
        ]:
            db.add(
                Trade(
                    account_id=order.account_id,
                    order_id=order.id,
                    instrument_id=order.instrument_id,
                    side=order.side,
                    quantity=order.filled_quantity,
                    price=order.average_price,
                )
            )
            # Update Position
            realized_pnl_delta = await OrderService._update_position(db, order)
            if realized_pnl_delta:
                db.add(
                    LedgerEntry(
                        account_id=order.account_id,
                        amount=realized_pnl_delta,
                        entry_type="REALIZED_PNL",
                        description=f"Realized P&L on {instrument.trading_symbol}",
                        reference_id=str(order.id),
                    )
                )

            # Update PnL
            await PnLEngine.mark_to_market_account(db, account)

            # Post-trade risk check
            await risk_engine.check_post_trade(db, account)

        await db.commit()
        await db.refresh(order)
        await broadcast_service.on_order_event(order.account_id)
        return order

    @staticmethod
    async def _update_position(db: AsyncSession, order: Order) -> Optional[Decimal]:
        """
        Updates the position for the account/instrument based on a filled order.
        Returns the realized P&L generated by this fill, if any.
        """
        if not order.average_price or order.filled_quantity == 0:
            return None

        stmt = select(Position).where(
            Position.account_id == order.account_id,
            Position.instrument_id == order.instrument_id,
        )
        result = await db.execute(stmt)
        position = result.scalar_one_or_none()

        if not position:
            position = Position(
                account_id=order.account_id,
                instrument_id=order.instrument_id,
                net_quantity=0,
                average_entry_price=order.average_price,
            )
            db.add(position)

        # Calculate new position
        qty_change = (
            order.filled_quantity
            if order.side == OrderSide.BUY
            else -order.filled_quantity
        )

        old_qty = position.net_quantity
        new_qty = old_qty + qty_change

        if old_qty == 0:
            position.net_quantity = new_qty
            position.average_entry_price = order.average_price
            return None
        elif (old_qty > 0 and qty_change > 0) or (old_qty < 0 and qty_change < 0):
            total_value = (abs(old_qty) * position.average_entry_price) + (
                order.filled_quantity * order.average_price
            )
            position.average_entry_price = total_value / abs(new_qty)
            position.net_quantity = new_qty
            return None
        else:
            closing_quantity = min(abs(old_qty), abs(qty_change))
            if old_qty > 0:
                realized_pnl = (
                    order.average_price - position.average_entry_price
                ) * closing_quantity
            else:
                realized_pnl = (
                    position.average_entry_price - order.average_price
                ) * closing_quantity
            position.realized_pnl += realized_pnl
            account = await db.get(Account, order.account_id)
            if account:
                account.realized_pnl += realized_pnl

            if new_qty == 0:
                position.net_quantity = 0
                position.average_entry_price = Decimal("0.00")
            elif abs(qty_change) > abs(old_qty):
                position.net_quantity = new_qty
                position.average_entry_price = order.average_price
            else:
                position.net_quantity = new_qty

            return realized_pnl
